language: cpp
compiler: gcc
sudo: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository ppa:zesty/libsfml -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5
  - sudo apt-get install libsfml-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make