language: cpp
compiler: gcc
sudo: true

install:
  # install SFML deps
  - sudo apt-get install libudev-dev
  - sudo apt-get install libopenal-dev
  # install g++
  - sudo apt-get install -qq g++-5
  # build and install SFML
  - mkdir sfml_install
  - wget http://www.sfml-dev.org/files/SFML-2.4.1-sources.zip --no-check-certificate
  - unzip -q SFML-2.4.1-sources.zip
  - pushd SFML-2.4.1 && mkdir build && cd build && cmake .. && make install
  - popd
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make