language: cpp

sudo: true

addons:
  apt:
    packages:
      - libudev-dev
      - libpthread-stubs0-dev
      - libgl1-mesa-dev
      - libx11-dev
      - libxrandr-dev
      - libfreetype6-dev
      - libglew1.5-dev
      - libjpeg8-dev
      - libsndfile1-dev
      - libopenal-dev
      - libflac-dev
      - libjpeg-dev
      - cmake

before_install:
  # build and install SFML
  - mkdir sfml_install
  - wget http://www.sfml-dev.org/files/SFML-2.4.1-sources.zip --no-check-certificate
  - unzip -q SFML-2.4.1-sources.zip
  - pushd SFML-2.4.1 && mkdir build && cd build && cmake .. && make && sudo make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake ..
  - make