language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris/cmake #backport cmake for ubuntu v12
    packages:
      - g++-5
      - cmake
      - libudev-dev
      - libpthread-stubs0-dev
      - libgl1-mesa-dev
      - libx11-dev
      - libxrandr-dev
      - libfreetype6-dev
      - libglew1.5-dev
      - libjpeg8-dev
      - libsndfile1-dev
      - libopenal-dev
      - libflac-dev
      - libjpeg-dev
cache:
  apt: true
  directories:
  - "$HOME/.travis/cmake/build/install"
  - "SFML-2.4.1"

before_install:
  - if [ "$CC"  == "gcc"     ]; then export CC=gcc-5; fi
  - if [ "$CXX" == "g++"     ]; then export CXX=g++-5; fi

install:
  - wget "http://www.sfml-dev.org/files/SFML-2.4.1-linux-gcc-64-bit.tar.gz" -O SFML.tar.gz
  - tar -xvf SFML.tar.gz
  - export PATH="$(pwd)/SFML-2.4.1:$PATH"
  - export SFML_ROOT="$(pwd)/SFML-2.4.1"
  - ./configure

script:
  - ./make