language: cpp
compiler: gcc
sudo: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install libudev-dev
  - sudo apt-get install -qq g++-5
  - mkdir sfml_install
  - wget http://www.sfml-dev.org/files/SFML-2.4.1-sources.zip --no-check-certificate
  - unzip -q SFML-2.4.1-sources.zip
  - pushd SFML-2.4.1 && mkdir build && cd build && cmake .. && make install
  - popd


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make